version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: msg-db
    environment:
      - POSTGRES_DB=msg
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5403:5432"
    networks:
      default:
        aliases:
          - msg-db

  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://msg-db:5432/msg
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "4000:4000"
      - "8080:8080"
    command: [ "./wait-for-it.sh","-t","0","msg-db:5432", "--","java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:4000","-jar","vehicles-rest-service.jar" ]
    depends_on:
      - db
    links:
      - db
